= functional and reactive programming for scalable architectures
Khaled Hafez & Mohamed Ragab
v3.11
:encoding: utf-8
:lang: en
///////////////////////
  AsciiDoc use `source-highlight` as default highlighter.

  Styles available for pygment highlighter:
  monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
  tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

  Uncomment following two lines if you want to highlight your code
  with `Pygments`.
///////////////////////
// :source-highlighter: coderay
:source-highlighter: pygments


// :source-highlighter: highlight
// :highlightjsdir: highlight
//:highlightjs-theme: github
//:pygments:
//:pygments-style: manni
// table or inline
//:pygments-linenums-mode: inline
//:src_numbered: numbered

:backend: revealjs
:revealjs_theme: night
//:revealjs_theme: simple
//:revealjs_center: false

// :backend: deckjs
//:deckjs_theme: neon
///////////////////////
  Transitions that you can choose includes:
  fade, horizontal-slide, vertical-slide
///////////////////////
// :deckjs_transition: fade
// :blank:
// :goto:
// :menu:
// :navigation:
// :status:
//:toc:
//:split:

== Bugs

Where do they come from

[source,scala,numbered]
----
println(s"$name: hello world\n")
println(s"$name: hello world\n")
----

== Slide One

[%step]
* Foo
* Bar
* World

== Slide One

[source,ruby,numbered]
----
ORDERED_LIST_KEYWORDS = {
  'loweralpha' => 'b',
  'lowerroman' => 'i',
  'upperalpha' => 'A',
  'upperroman' => 'I'
   #'lowergreek' => 'a'
   #'arabic'     => '1'
   #'decimal'    => '1'
}
----

== Slide 1.1

Does this work here?

=== Slide 1.2

Does this work here?

=== Slide 1.3

Does this work here?

== Slide Two

Hello World - Good Bye Cruel World

A might not be that cruel world after all

== Slide Three

How about a third slide

[%step]
* With
* A few
* Bullets
* In steps


++++
<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
++++
